language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

services:
  - mysql

before_script:
  - mysql -e "CREATE USER 'aixada'@'localhost' IDENTIFIED BY 'aixada';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON aixada.* TO 'aixada'@'localhost';" -uroot
  - find . -name "*.php" -type f -exec php -l {} \;
  - composer update
  - cp local_config/config.php.sample local_config/config.php
